name: Manual deploys (for any environment or product)

on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name to be deployed (app/app2)'
        required: true
        default: '-'
      build_src:
        description: 'Source folder to be deployed (package/app/build, package/lib/lib)'
        required: true
        default: '-'
      tag:
        description: 'Tag version to be deployed (1.0.0-dev.0, 2.1.1)'
        required: true
        default: '-'
      env:
        description: 'Environment to be deployed (dev, staging, production)'
        required: true
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout specific package tag release
        run: git checkout -b deploy-${{ github.event.inputs.package }}@${{ github.event.inputs.tag }} ${{ github.event.inputs.package }}@${{ github.event.inputs.tag }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.7.0'
          registry-url: https://npm.pkg.github.com
          scope: '@davikawasaki'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # - run: npm run build
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      #     CI: true
      # - name: Deploy to S3 production bucket
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     # todo: change this when production deploy comes to play
      #     AWS_S3_BUCKET: 'bucketname_production'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'sa-east-1'           # optional: defaults to us-east-1
      #     SOURCE_DIR: ${{ github.event.inputs.build_src }}  # optional: defaults to entire repository
      #   if: contains('production', github.event.inputs.env)
      # - name: Deploy to S3 dev bucket
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     # todo: change this when production deploy comes to play
      #     AWS_S3_BUCKET: 'bucketname_production'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'sa-east-1'           # optional: defaults to us-east-1
      #     SOURCE_DIR: ${{ github.event.inputs.build_src }}  # optional: defaults to entire repository
      #   if: contains('dev', github.event.inputs.env)
      # - name: Invalidate production CDN distribution 
      #   uses: awact/cloudfront-action@master
      #   env:
      #     AWS_REGION: 'sa-east-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      #     DISTRIBUTION_ID: '123ABC_production'
      #   if: contains('production', github.event.inputs.env)
      # - name: Invalidate testing CDN distribution 
      #   uses: awact/cloudfront-action@master
      #   env:
      #     AWS_REGION: 'sa-east-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      #     DISTRIBUTION_ID: '123ABC_testing'
      #   if: contains('production', github.event.inputs.env)